[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.13.0"
nom = "7.1.3"
num_cpus = "1.16.0"
rayon = "1.10.0"
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }
